import { Player } from '../interfaces/Player';

export const players: Player[] = [
  { name: 'benzema', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'lewa', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'mbappe', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'messi', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'mane', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'neymar', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'kane', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'haaland', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'salah', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'ronaldo', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'son', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'vinny', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'dybala', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'nkunku', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'depay', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'griezmann', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'lukaku', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'coman', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'mahrez', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'foden', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'jota', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'sterling', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'dembele', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'carrasco', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'osimhen', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'leao', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'chiesa', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'di maria', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'diaby', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'sane', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'ben yedder', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'luiz diaz', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'g jesus', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'saka', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'hazard', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'vardy', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'felix', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'zlatan', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'werner', position: 'POS', role: 'ATK', overall: 0 },
  { name: 'marquinhos', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'ruben dias', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'rüdiger', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'cancelo', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'robertson', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'alaba', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'skrtel', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'laporte', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'arnold', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'koulibaly', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'j alba', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'theo hernandez', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'süle', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'de ligt', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'varane', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'walker', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'militao', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'carvajal', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'kounde', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'tomori', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'davies', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'hakimi', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'james', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'grimaldo', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'mendy (bek)', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'kimpembe', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'upamecano', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'mazraoui', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'van dijk', position: 'POS', role: 'DEF', overall: 0 },
  { name: 'kdb', position: 'POS', role: 'MID', overall: 0 },
  { name: 'kimmich', position: 'POS', role: 'MID', overall: 0 },
  { name: 'casemiro', position: 'POS', role: 'MID', overall: 0 },
  { name: 'modric', position: 'POS', role: 'MID', overall: 0 },
  { name: 'bernardo silva', position: 'POS', role: 'MID', overall: 0 },
  { name: 'kante', position: 'POS', role: 'MID', overall: 0 },
  { name: 'de jong', position: 'POS', role: 'MID', overall: 0 },
  { name: 'goretzka', position: 'POS', role: 'MID', overall: 0 },
  { name: 'verratti', position: 'POS', role: 'MID', overall: 0 },
  { name: 'rodri', position: 'POS', role: 'MID', overall: 0 },
  { name: 'parejo', position: 'POS', role: 'MID', overall: 0 },
  { name: 'valverde', position: 'POS', role: 'MID', overall: 0 },
  { name: 'milinkovic-savic', position: 'POS', role: 'MID', overall: 0 },
  { name: 'brozovic', position: 'POS', role: 'MID', overall: 0 },
  { name: 'barella', position: 'POS', role: 'MID', overall: 0 },
  { name: 'bruno fernandes', position: 'POS', role: 'MID', overall: 0 },
  { name: 'thiago', position: 'POS', role: 'MID', overall: 0 },
  { name: 'fabinho', position: 'POS', role: 'MID', overall: 0 },
  { name: 'pedri', position: 'POS', role: 'MID', overall: 0 },
  { name: 'fekir', position: 'POS', role: 'MID', overall: 0 },
  { name: 'pogba', position: 'POS', role: 'MID', overall: 0 },
  { name: 'bellingham', position: 'POS', role: 'MID', overall: 0 },
  { name: 'ilkay', position: 'POS', role: 'MID', overall: 0 },
  { name: 'odegaard', position: 'POS', role: 'MID', overall: 0 },
  { name: 'kessie', position: 'POS', role: 'MID', overall: 0 },
  { name: 'tonali', position: 'POS', role: 'MID', overall: 0 },
  { name: 'çavmeni', position: 'POS', role: 'MID', overall: 0 },
  { name: 'kurtua', position: 'POS', role: 'GK', overall: 0 },
  { name: 'oblak', position: 'POS', role: 'GK', overall: 0 },
  { name: 'neuer', position: 'POS', role: 'GK', overall: 0 },
  { name: 'ederson', position: 'POS', role: 'GK', overall: 0 },
  { name: 'alisson', position: 'POS', role: 'GK', overall: 0 },
  { name: 'ter stegen', position: 'POS', role: 'GK', overall: 0 },
  { name: 'donnarumma', position: 'POS', role: 'GK', overall: 0 },
  { name: 'maignan', position: 'POS', role: 'GK', overall: 0 },
  { name: 'navas', position: 'POS', role: 'GK', overall: 0 },
  { name: 'de gea', position: 'POS', role: 'GK', overall: 0 },
  { name: 'lloris', position: 'POS', role: 'GK', overall: 0 },
  { name: 'mendy (gk)', position: 'POS', role: 'GK', overall: 0 },
];
